# permissions for end users to edit contracts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: contract-editor-role
rules:
- apiGroups:
  - cache.adamg.com
  resources:
  - contracts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.adamg.com
  resources:
  - contracts/status
  verbs:
  - get
