# permissions for end users to view contracts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: contract-viewer-role
rules:
- apiGroups:
  - cache.adamg.com
  resources:
  - contracts
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.adamg.com
  resources:
  - contracts/status
  verbs:
  - get
