
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cache.adamg.com
  resources:
  - contracts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.adamg.com
  resources:
  - contracts/finalizers
  verbs:
  - update
- apiGroups:
  - cache.adamg.com
  resources:
  - contracts/status
  verbs:
  - get
  - patch
  - update
